### ISSUE TITLE
[Bug] Stuck "waiting for # mods to finish packing"

### ISSUE THREAD

**Issue by aschmois** [zlepper/TechnicSolderHelper#49] opened 2015-04-05 13:41 UTC
![](http://i.imgur.com/CoLqNvM.png)

I've tried almost everything to fix this. I've got about 200 mods but only 137 get done.

**Comment by zlepper** [comment] 2015-04-05 14:41
Could you zip up the entire thing and send to me so I can try? I can't reproduce the issue with my setup, so I would like to try with your mods.

**Comment by aschmois** [comment] 2015-04-05 15:25
It's uploading now, while we wait, I think I found the issue. It's the mods with similar names. Looking into your db, ftbperms seems to have a lot of identical names for different mods. ProjectRed for example, has a shortname of projectred for all components of the mod. Somehow I was able to do it one time (I've been trying for hours) and I saw that it was making it be different versions instead of different mods.

I went into the db manually and changed those that were causing issues for me, and now it works but it still packages all different components into the same zip file but telling solder that they are different mods.

**Comment by aschmois** [comment] 2015-04-05 15:27
![](http://i.imgur.com/raKgsP0.png)

This is what I see as tmp when the program seems to crash. Half the time, it doesn't crash but it doesn't add any mods.

**Comment by aschmois** [comment] 2015-04-05 15:32
Ok I've uploaded the files to http://android305.com:8000/mods.7z

It's a little on the larger side, which is the main reason for trying to use your helper (awesome program btw), so if you feel like it's too much, I can go ahead and let you in remotely on my computer. Just let me know what you would like to do.

**Comment by zlepper** [comment] 2015-04-05 15:35
I'll see what I can do about the issue. though I seem to be hitting an early wall, and once i'm around that one i'll see if I can find the actual issue you have.

**Comment by zlepper** [comment] 2015-04-05 18:27
As of this message I just published those changes. Please check and see if they fixes the issue.

**Comment by aschmois** [comment] 2015-04-05 18:29
You won't believe what I've been through all night. My computer just
completely died. I'm currently reseating my CPU and memory testing all my
RAM. I will test it out as soon as I can get my computer running again.
Thanks for the quick fix.

**Comment by zlepper** [comment] 2015-04-05 18:49
I wish you good luck then

**Comment by aschmois** [comment] 2015-04-05 19:10
Thank you, my computer is alive! I've tried it out, with no luck. Same weird behavior. Everything seems to work, but I've got no mods in the output.

While going to write this issue, out of nowhere I got Waiting for 142 mods to finish packing, and again program is no longer responding.

**Comment by zlepper** [comment] 2015-04-05 19:24
SolderHelper tries to remember which mods you already put in solder by storing them in a local database, but if you hit reset database it will repack everything, without you having to reenter it all. 
And if some files are already added to Solder, then it will also skip packing those files to avoid having to reupload something that is already there.

**Comment by aschmois** [comment] 2015-04-05 21:18
Yeah that was it. Now I'm getting results! However, the project red example is still broken.

The following mods get packaged together
- buildcraft and buildcraft-compat
    - two zip files with both mods in both zip files
- growthcraft (and all of its counter parts, weird results here)
- project red (and all of its counter parts)


![](http://i.imgur.com/q6pwRB4.png)
![](http://i.imgur.com/WNtv6A1.png)
![](http://i.imgur.com/q8q05yK.png)
![](http://i.imgur.com/9Aoxgem.png)
![](http://i.imgur.com/Rexv4Az.png)
![](http://i.imgur.com/h0jOwjC.png)

**Comment by aschmois** [comment] 2015-04-05 21:20
and even when getting results, the program stops responding randomly.

![](http://i.imgur.com/aa8ubDq.png)

**Comment by zlepper** [comment] 2015-04-06 09:16
While it's packing mods the interface will stop responding simply because it takes so long to pack everything.
And it's not an accident that it puts all the project red mods in the same folder, they always update at the same time, so there is nothing lost in doing it, actually it would be way more difficult to not do it like that.

**Comment by zlepper** [comment] 2015-04-06 09:22
I'll see if I can fix the issue with buildcraft.

**Comment by zlepper** [comment] 2015-04-06 09:30
And fixed in latest.

**Closed by zlepper** 2015-04-06 09:30 UTC
Labels: bug
